namespace Tetris;

internal record GameSettings(
    string Nick,
    int StartLevelIndex,
    int GameModeIndex,
    int ThemeIndex,
    double MusicVolume,
    double EffectsVolume,
    int DasMs,
    int ArrMs,
    int SoftDropArrMs,
    string MoveLeftKey,
    string MoveRightKey,
    string SoftDropKey,
    string RotateKey,
    string HardDropKey,
    string HoldKey,
    bool ColorblindMode,
    bool? ShowSessionStats,
    bool? MusicEnabled,
    bool? EffectsEnabled,
    bool? LockParticlesEnabled,
    string? AdminPassword,
    string? LanguageCode);
